name: Build and Deploy PDFs

on:
  push:
    branches:
      - main  # Déclenche le workflow à chaque push sur la branche principale

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up LaTeX environment
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full

      - name: Compile LaTeX documents
        run: |
          mkdir -p pdfs
          find . -name "*.tex" -exec latexmk -pdf -interaction=nonstopmode -file-line-error -output-directory=pdfs {} \;

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: pdfs
